config/routes.rb
Rails.application.routes.draw do
  get 'session/login'

  post 'session/create'

  get 'session/logout'

  resources :users
  root to: 'logic#input'

  get 'logic/input'

  get 'logic/output'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    alias_attribute :password_digest, :password_hash
    has_secure_password

    def self.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def self.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  include SessionHelper

  private

  def require_login
      unless signed_in?
          flash[:danger] = "Необходимо войти"
          redirect_to session_login_path
      end
  end

end

app/controllers/logic_controller.rb
class LogicController < ApplicationController
    def armstrong_number?(arg)
      number = arg.to_s.length
      arg == arg.to_s.split('').map(&:to_i).map { |elem| elem**number }.inject(&:+)
    end

  def input
  end

  def output
        if params[:param] == '' || params[:param].to_i.nil? || params[:param].to_i.zero?
          @result = 'There is no data or the data is incorrect'
          nil
        else
          @result = []
          ((10**(params[:param].to_i - 1))..(10**params[:param].to_i - 1))
            .each do |i|
            @result << i if armstrong_number?(i)
          end
        end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    skip_before_action :require_login, only: [:login, :create]
  def login
  end

  def create
      user = User.find_by_email(params[:email])

      if user&.authenticate(params[:password])
          sign_in user
          redirect_to root_path
      else
          flash.now[:danger] = "Неверный логин/пароль"
          redirect_to session_login_path
      end
  end

  def logout
      cookies.permanent[:remember_token] = nil
      redirect_to session_login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:new, :create]

  def index
      @users = User.all
  end

  def edit
  end

  def new
      @user = User.new
  end

  def show
  end

  def create
      @user = User.new(user_params)
      respond_to do |format|
          if @user.save
              sign_in @user
              format.html { redirect_to @user, notice: 'User was created' }
              format.json { render :show, status: :created, location: @user }
          else
              format.html { render :new }
              format.json {render json: @user.errors, status: :unprocessable_entity }
          end
      end
  end

  def update
      respond_to do |format|
          if @user.update(user_params)
              format.html { redirect_to @user, notice: 'User was updated' }
              format.json { render :show, status: :ok, location: @user }
          else
              format.html { render :edit }
              format.json { render json: @user.errors, status: :unprocessable_entity }
          end
      end
  end

  def destroy
      @user.destroy
      respond_to do |format|
          format.html { redirect_to users_url, notice: 'User was deleted' }
          format.json { head :no_content }
      end
  end

  private

  def set_user
      @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logic_helper.rb
module LogicHelper
end

app/helpers/session_helper.rb
module SessionHelper

    def sign_in(user)
        remember_token = User.new_remember_token
        cookies.permanent[:remember_token] = remember_token
        user.update_attribute(:remember_token, User.encrypt(remember_token))
        self.current_user = User
    end

    def signed_in?
        !current_user.nil?
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        remember_token = User.encrypt(cookies[:remember_token])
        @current_user ||= User.find_by(remember_token: remember_token)
        #@current_user ||= User.where( remember_token: remember_token).first
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr12</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'partials/nav' %>

  <body>
    <div class="container" id="main-container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/logic/input.html.erb
<h1>Lab 8</h1>


<%= form_tag('/logic/output', :method => 'get') do %>

    <!--<%= label_tag('Введите N') %> <br> -->
    <div class="form-row">
    <h3><%=text_field_tag(:param, nil, placeholder: 'введите количество разрядов', class: 'form-control col') %> </h3>
    </div>
    <h3><%=submit_tag('Calculate', class: 'btn btn-primary')%> </h3>

<%end%>

app/views/logic/output.html.erb
<h1>Result of calculations</h1>

<% if @result != 'There is no data or the data is incorrect'%>
<table class="table table-striped">
  <thead>
  <th scope="col">#</th>
  <th scope="col">Value</th>
  </thead>
  <tbody>
  <% @result.each_with_index do |elem, index| %>
  <tr>
    <th scope="row"><%= index+1 %></th>
    <td><%= elem %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<% else %>
<h2><%= @result %></h2>
<% end %>

<%= form_tag('/logic/input', :method => 'get') do %>
    <%= submit_tag('Назад', class: 'btn btn-primary') %>
<% end %>

app/views/partials/_flash.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<% flash.each do |message_type, message| %>

    <div class="row">

      <div class="col">

        <div class="alert alert-<%= message_type %> alert-dismissible fade show" role="alert">

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>

          <%= message.html_safe %>

        </div>

      </div>

    </div>

<% end %>

app/views/partials/_nav.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

<nav class="navbar-expand-lg navbar navbar-dark bg-primary">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
   </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

    <div class="navbar-nav">

      <a class="nav-item nav-link active" href="<%= root_path %>">Главная</a>

      <% if signed_in? %>

        <a class="nav-item nav-link active" href="<%= session_logout_path %>">Выход</a>

      <% else %>

        <a class="nav-item nav-link active" href="<%= new_user_path %>">Регистрация</a>
        <a class="nav-item nav-link active" href="<%= session_login_path %>">Вход</a>

      <% end %>

    </div>

  </div>

</nav>

app/views/session/login.html.erb
<%= render 'partials/flash' %>



<%= form_tag url_for(controller: :session, action: :create), method: 'post' do %>
<div class="form-group">
    <%= label_tag 'email' %>
    <%= text_field_tag(:email, nil, placeholder: 'Введите e-mail', class: 'form-control', type: 'email') %>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
</div>

<div class="form-group">
    <%= label_tag 'password'  %>
    <%= password_field_tag 'password', class:'form-control', type: 'password', placeholder: 'Password' %><br />
</div>

<%= submit_tag 'Login', class: 'btn btn-outline-primary' %><br />

<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
    <div class="field" type="password">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, placeholder: 'Введите email', type: 'email' %>
    </div>

    <div class="field" type="password">
      <%= form.label :password %>
      <%= form.text_field :password, id: :user_password, type: 'password' %>
    </div>

    <div class="field" type="password">
      <%= form.label :password_confirmation %>
      <%= form.text_field :password_confirmation, id: :user_password_confirmation, type: 'password' %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-outline-primary' %>
    </div>
</div>

<% end %>

app/views/users/edit.html.erb
<h1>User editor</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice">
    <%= notice %>
</p>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path, class: 'btn btn-outline-secondary' %>

app/views/users/show.html.erb
<p id="notice">
    <%= notice %>
</p>

<p>
    <strong>Email:</strong>
    <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-secondary' %> |
<%= link_to 'Back', users_path,class: 'btn btn-outline-secondary' %>